// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-hN1ydKSU5GnzzngofM9XJrBpvGjC2ak',
    appId: '1:900697143007:web:1013a72bdec55f955f1b6a',
    messagingSenderId: '900697143007',
    projectId: 'custom-7d54c',
    authDomain: 'custom-7d54c.firebaseapp.com',
    storageBucket: 'custom-7d54c.firebasestorage.app',
    measurementId: 'G-9ZEM2NMZ8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDONJlb6DIMWCmDGOlfxUWyjNwQo4a4e38',
    appId: '1:900697143007:android:625ea72b6091724b5f1b6a',
    messagingSenderId: '900697143007',
    projectId: 'custom-7d54c',
    storageBucket: 'custom-7d54c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTPQmEL9Hmm553W-FOy79uXvGy8WnM46Q',
    appId: '1:900697143007:ios:b1c1705a06663c085f1b6a',
    messagingSenderId: '900697143007',
    projectId: 'custom-7d54c',
    storageBucket: 'custom-7d54c.firebasestorage.app',
    iosBundleId: 'com.example.custom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTPQmEL9Hmm553W-FOy79uXvGy8WnM46Q',
    appId: '1:900697143007:ios:b1c1705a06663c085f1b6a',
    messagingSenderId: '900697143007',
    projectId: 'custom-7d54c',
    storageBucket: 'custom-7d54c.firebasestorage.app',
    iosBundleId: 'com.example.custom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-hN1ydKSU5GnzzngofM9XJrBpvGjC2ak',
    appId: '1:900697143007:web:87f501f40d909eb75f1b6a',
    messagingSenderId: '900697143007',
    projectId: 'custom-7d54c',
    authDomain: 'custom-7d54c.firebaseapp.com',
    storageBucket: 'custom-7d54c.firebasestorage.app',
    measurementId: 'G-44SP953RS9',
  );
}
